In [2]:
from warnings import filterwarnings

filterwarnings("ignore")

In [3]:
a = [1, 2, 3, 5, 6]
type(a)

list

In [4]:
import numpy as np

In [7]:
a1 = np.array(a)
a1

array([1, 2, 3, 5, 6])

In [8]:
a1.ndim

1

In [9]:
a1 * 2

array([ 2,  4,  6, 10, 12])

In [10]:
a1 ** (1 / 2)

array([1.        , 1.41421356, 1.73205081, 2.23606798, 2.44948974])

In [11]:
e = np.linspace(2, 10, 3)

In [12]:
e

array([ 2.,  6., 10.])

In [13]:
np.random.random()

0.9306790569867741

In [14]:
np.random.randint(1, 7)

1

In [17]:
d = np.random.randint(2, 10, 20)
d

array([9, 8, 3, 4, 4, 5, 3, 7, 7, 4, 2, 8, 6, 2, 3, 3, 5, 5, 9, 8],
      dtype=int32)